# Railway Configuration File
[project]
name = "fastapi-app"

[build]
# Set the build environment
pythonVersion = "3.9"

[deploy]
start = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[services]
  [services.web]
  startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
  healthCheckPath = "/"
